In [21]:
import pandas as pd
import torch

In [15]:
data = pd.read_csv('../../data/house_tiny.csv')

data

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000

In [16]:
inputs, targets = data.iloc[:, :2], data.iloc[:, 2]

inputs.shape, targets.shape

((4, 2), (4,))

In [17]:
display(inputs)

inputs = pd.get_dummies(inputs, dummy_na=True)

inputs

   NumRooms RoofType
0       NaN      NaN
1       2.0      NaN
2       4.0    Slate
3       NaN      NaN

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True

In [19]:
inputs = inputs.fillna(inputs.mean())

inputs

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True

In [22]:
X = torch.tensor(inputs.to_numpy(dtype=float))
Y = torch.tensor(targets.to_numpy(dtype=float))

X, Y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))